* CAN YILMAZ ALTINÝÐNE - 150130132
* ÝKÝ AYRI DÝZÝNÝN ELEMANLARI BÝRER BÝRER YENÝ BÝR DÝZÝYE YAZMA

	BAÞ	$500
	VER	$0,$1,$2,$3,$4,$5,$6,$7,$8,$9,$A,$B,$C,$D,$E,$F
	BAÞ	$550
	VER	$B0,$B1,$B2,$B3,$B4,$B5,$B6,$B7,$B8,$B9,$BA,$BB,$BC,$BD,$BE,$BF
	BAÞ	$300

* 500 ADRESÝNDEN ÝTÝBAREN SÝYAH SAYILAR YAZILMIÞTIR
* 550 ADRESÝNDEN ÝTÝBAREN BEYAZ SAYILAR BAÞINDA B OLACAK ÞEKÝLDE BELLEÐE YAZILMIÞTIR
* PROGRAM 300 ADRESÝNDEN BAÞLAYACAK ÞEKÝLDE BELLEÐE YAZILMIÞTIR

BAÞLA	YÜK SK, $600		SON DÝZÝ 600 ADRESÝNDEN BAÞLAYACAKTIR 600 ADRESÝ 100 ADRESÝNE YAZILMIÞTIR
	YAZ SK, <$100>
	YÜK A, $10			$10 SAYISI (BÝR DÝZÝNÝN UZUNLUÐU) 102 ADRESÝNE YAZILMIÞTIR
	YAZ A, <$102>
	YÜK SK, $500		SÝYAH BAÞLANGIÇ ADRESÝ (500) 104 ADRESÝNE YAZILMIÞTIR
	YAZ SK, <$104>
	YÜK SK, $550		BEYAZ BAÞLANGIÇ ADRESÝ (550) 106 ADRESÝNE YAZILMIÞTIR
	YAZ SK, <$106>
	YÜK A, <$102>		DÝZÝ UZUNLUÐU OKUNUP
	TOP A, $10			KENDÝSÝYLE TOPLANARAK EN SONDA OLUÞACAK DÝZÝNÝN UZUNLUÐU BULUNMUÞTUR
	AKT B, A			BU UZUNLUK ACC B'YE AKTARILMIÞTIR

KARIÞ	YÜK SK, <$104>		104 ADRESÝ OKUNARAK SK'YA SÝYAH BAÞLANGICI (500) ATANMIÞTIR
	YÜK A, <SK+00>+1		A'YA 500 ADRESÝNDEKÝ ÝLK SÝYAH ELEMANI YÜKLENMÝÞTÝR SK 1 ARTIRILMIÞTIR
	YAZ SK, <$104>		ÖNCEDEN SÝYAH BAÞLANGICI TUTAN YERE BÝR SONRAKÝ SÝYAH ELEMANIN ADRESÝ YAZILMIÞTIR
	YÜK SK, <$100>		100 ADRESÝNDEN FÝNAL DÝZÝNÝN ADRESÝ SK'YA YÜKLENMÝÞTÝR
	YAZ A, <SK+00>+1		ACC A FÝNAL DÝZÝNÝN ÝLK ADRESÝNE ATANMIÞTIR SK 1 ARTIRILMIÞTIR
	YAZ SK, <$100>		100 ADRESÝ ARTIK FÝNAL DÝZÝNÝN SIRADAKÝ ADRESÝNÝ GÖSTERÝR 
	AZT B				B AZALTILMIÞTIR (OKUNACAK SAYI MÝKTARI)
	DEE BÝTTÝ			EÐER OKUNACAK SAYI KALMADIYSA BÝTÝÞE DALLANILACAKTIR
	YÜK SK, <$106>		YUKARIDAKÝ AYNI ÞEYLER ÞÝMDÝ BEYAZ SAYILAR ÝÇÝN YAPILIR
	YÜK A, <SK+00>+1
	YAZ SK, <$106>
	YÜK SK, <$100>
	YAZ A, <SK+00>+1
	YAZ SK, <$100>
	AZT B
	DEE BÝTTÝ
	DAL KARIÞ			EÐER DAHA OKUNACAK SAYI VARSA BEYAZ SAYIDAN OKUNMAYA BAÞLANACAK YERE DALLANILIR

BÝTTÝ	KES