* CAN YILMAZ ALTINÝÐNE - 150130132
* SAÐA - SOLA LED YAKMA

	BAÞ $300
BAÞLA	YAZ $FF, <YÖNLEN.B>			PÝA B VERÝCÝ OLARAK AYARLANDI
	YÜK A, $01					%00000001 YÜKLE ÝLK LED ÝÇÝN
	YAZ A, <ÝSKELE.B>
	
SODÖN	SOL A						SOLA DÖNDÜR
	ALT BEKLE					BEKLEME PROGRAMINA DALLAN
	YAZ A, <ÝSKELE.B>				BEKLEDÝKTEN SONRA YENÝ DEÐERÝ ÝSKELEYE YAZ 
	KAR A, $80					EÐER SOLDAN EN BAÞTAKÝ LED YANDIYSA SAÐA DÖNMEYE BAÞLA
	DEE SADÖN					DEÐÝLSE SOLA DÖNÜÞE DEVAM
	DAL SODÖN

SADÖN	SAÐ A						SOLA DÖNÜÞ ÝÇÝN AYNI MANTIK EÐER ACC A 01 ÝSE YANÝ SAÐDAN ÝLK LED YANDIYSA
	ALT BEKLE					SOLA DÖNMEYE DALLAN
	YAZ A, <ÝSKELE.B>
	KAR A, $01
	DEE SODÖN
	DAL SADÖN

BEKLE YÜK CD, $0					BEKLEME ALT PROGRAMI
BÝR	ART CD					CD'YÝ ÖNCE $0'DAN $FFFF'E KADAR ARTIR
	KAR CD, $FFFF
	DEE ÝKÝ
	DAL BÝR
ÝKÝ   YÜK CD, $0					SONRA YÝNE $0'DAN $7FFF'E KADAR ARTIR
ARTIR	ART CD					BÖYLE YAPARAK KENDÝ BÝLGÝSAYARIMDA YAKLAÞIK 1 SANÝYE BEKLEME SÜRESÝNÝ YAKALADIM
	KAR CD, $7FFF
	DEE BÝTÝÞ
	DAL ARTIR
BÝTÝÞ	DÖN
