* CAN YILMAZ ALTINÝÐNE - 150130132
* BÝR DÝZÝ ÜSTÜNDE KABARCIK SIRALAMA	
		
		BAÞ 	$500
		VER 	$1,$93,$15,$FC,$DB,$0,$3D,$CA,$67,$9C,$10,$E9,$59,$89,$B6,$6F,$BE,$51,$47
		VER	$2D,$32,$D1,$80,$18,$EA,$72,$C8,$FB,$7E,$5,$A7,$30,$28,$5D,$EF,$4E,$22
		BAÞ 	$300	

* SIRALANMAMIÞ DÝZÝ 500 ADRESÝNDEN BAÞLAYACAK ÞEKÝLDE YAZILDI
* SIRALANMIÞ DÝZÝ 104 ADRESÝNDEN BAÞLAYACAK ÞEKÝLDE YAZILDI				

BAÞLA		YÜK SK, $500		100 NUMARALI ADRESE 500 (SIRALANMAMIÞ BAÞLANGIÇ) YAZILDI
		YAZ SK, <$100>	
		YAZ $25, <$102>		102 NUMARALI ADRESE DÝZÝ UZUNLUÐU YAZILDI
		YAZ $25, <$700>		ÝLERÝDE BU UZUNLUÐU BAÞKA BÝR YERDE KULLANMAK ÝÇÝN UZUNLUK 700'E DE YAZILDI
		YÜK SK, $500		KOPYALAMA ÝÞLEMÝ ÝÇÝN SK'YA SIRALANMAMIÞ BAÞLANGIÇ VE CD'YE SIRALANACAK DÝZÝNÝN
		YÜK CD, $104		BAÞLANGIÇ ADRESÝ YAZILDI

KOPYALA	YÜK A, <SK+00>+1		500 ADRESÝNDEN BAÞLAYAN SIRALANMAMIÞ DÝZÝ 104'TEN BAÞLAYACAK ÞEKÝLDE KOPYALANIYOR
		YAZ A, <CD>
		ART CD
		KAR SK, $525		
		DEK KOPYALA			EÐER $25 SAYISINA ULAÞILMADIYSA KOPYALAMAYA DEVAM
		YÜK C, $1			KOPYALAMA BÝTTÝKTEN SONRA C VE D KULLANILMAK ÜZERE BAÞLANGIÇ DEÐERLERÝ YÜKLENÝYOR
		SÝL D
		DAL BÝRÝNCÝ			BÝRÝNCÝ KONTROLE DALLANILIYOR

BÝRÝNCÝ	YÜK SK, $104		BUBBLE SORT ÝKÝ FOR DÖNGÜSÜYLE YAPILDIÐI ÝÇÝN BÝRÝNCÝ VE ÝKÝNCÝ OLMAK ÜZERE
		YÜK A, $1			ÝKÝ KONTROL YERÝ PROGRAMA YAZILIYOR
		KAR C, <$102>		EÐER C $25 SAYISINA ULAÞTIYSA BÝTÝÞ DALLANILIYOR
		DEE BÝTÝÞ			DEÐÝLSE ÝKÝNCÝ DÖNGÜ KISMINA DALLANILIYOR
		DAL ÝKÝNCÝ			ÝLK DÖNGÜNÜN $25 SAYI BULUNDUÐUNDAN $24 KERE DÖNMESÝ GEREKÝR
		
ÝKÝNCÝ	KAR A, <$700>		ÝKÝNCÝ DÖNGÜDE ÝLERÝDE KULLANACAÐIMIZ DEDÝÐÝMÝZ DEÐÝÞKENLE A'YI KARÞILAÞTIRIYORUZ
		DEE ÝKÝTAMAM		EÐER A BU SAYIYA ULAÞTIYSA ÝKÝNCÝ DÖNGÜNÜN TAMAMLANDIÐINI BÝLÝYORUZ 
		YÜK B, <SK+00>+1		B'YE SK'DAKÝ SAYI D'YE BÝR SONRAKÝ SAYI YÜKLENÝYOR
		YÜK D, <SK+00>
		KAR B,D			EÐER ÖNCEKÝ SAYI SONRAKÝ SAYIDAN BÜYÜKSE DEÐÝÞMEYE DALLANILIYOR
		DEB DEÐÝÞ
		DAL KONTROL			DEÐÝLSE KONTROLE DALLANILIYOR

DEÐÝÞ		AZT SK			SK BÝR ÝLERÝDE OLDUÐU ÝÇÝN SK AZALTILIYOR
		YAZ D, <SK+00>+1		KÜÇÜK SAYI SK'YA BÜYÜK SAYI SK+1'E YAZILIYOR VE YER DEÐÝÞTÝRME SAÐLANIYOR
		YAZ B, <SK+00>
		DAL KONTROL			KONTROLE DALLANILIYOR

KONTROL	ART A				A BÝR ARTIRILIYOR VE ÝKÝNCÝ DÖNGÜNÜN KONTROLÜ ÝÇÝN ÝKÝNCÝ'YE DALLANILIYOR
		DAL ÝKÝNCÝ

ÝKÝTAMAM	AZT <$700>			EÐER ÝKÝ TAMAMSA 700'DE KULLANDIÐIMIZ DEÐER BÝR AZALTILIYOR
		ART C				ÝKÝ TAMAMLANINCA BÝRDEKÝ DÖNGÜNÜN BÝR ADIMI TAMAMLANDIÐI ÝÇÝN C BÝR ARTIRILIYOR
		DAL BÝRÝNCÝ			VE KONTROL ÝÇÝN BÝRÝNCÝYE DALLANILIYOR
	
BÝTÝÞ		KES


* ÝLK DÖNGÜMÜZ $24 KERE DÖNMEK ZORUNDADIR
* ÝKÝNCÝ DÖNGÜMÜZ ÝSE ÝLK DÖNGÜNÜN ÝLK ADIMINDA $24, ÝKÝNCÝ ADIMINDA $23 OLACAK ÞEKÝLDE AZALARAK DÖNECEKTÝR
* SONUNDA 500'DEN BAÞLAYACAK ÞEKÝLDE DÜZENSÝZ DÝZÝ, 104'DEN BAÞLAYACAK ÞEKÝLDE SIRALI DÝZÝ BELLEKTE BULUNUR



	