* CAN YILMAZ ALTINÝÐNE - 150130132
* DAÝRESEL LED YAKMA
	
	BAÞ $300
BAÞLA	YAZ $FF, <YÖNLEN.B>			PÝA B VERÝCÝ
	YÜK A, $01					SAÐDAN ÝLK LED YANMASI ÝÇÝN $01 YÜKLENDÝ
	YAZ A, <ÝSKELE.B>				ÝSKELEYE DEÐER YÜKLENDÝ 
	DAL SODÖN					SOLA DÖNMEYE BAÞLADI

REW	YÜK A, $01					TEKRAR ACC A'YA $01 YAZ
	ALT BEKLE					BEKLEME PROGRAMINA DALLAN
	YAZ A, <ÝSKELE.B>				ÝSKELEYE DEÐERÝ YAZ SAÐDAN EN BAÞTAKÝ LEDÝ YAKMAK ÝÇÝN
	
SODÖN	SOL A						SOLA DÖNDÜR
	ALT BEKLE					BEKLEME ALT PROGRAMINA DALLAN
	YAZ A, <ÝSKELE.B>				ÝSKELEYE YENÝ DEÐERÝ YAZ
	KAR A, $80					EÐER SOLDAN EN BAÞTAKÝ LED YANDIYSA
	DEE REW					REW'E DALLAN TEKRAR SAÐDAN EN BAÞTAKÝ LEDÝ YAKMAK ÝÇÝN
	DAL SODÖN					DEÐÝLSE SOLA DÖNDÜRMEYE DEVAM

BEKLE YÜK CD, $0					BEKLEME ALT PROGRAMI
BÝR	ART CD					CD'YÝ ÖNCE 0'DAN FFFF'E KADAR ARTIR
	KAR CD, $FFFF				SONRA CD'YÝ YÝNE 0'DAN 7FFF'E KADAR ARTIR
	DEE ÝKÝ					KENDÝ BÝLGÝSYARIMDA BÖYLE YAPARAK 1 SANÝYE BEKLEME SÜRESÝ ELDE ETTÝM
	DAL BÝR
ÝKÝ   YÜK CD, $0
ARTIR	ART CD
	KAR CD, $7FFF
	DEE BÝTÝÞ
	DAL ARTIR
BÝTÝÞ	DÖN
