* CAN YILMAZ ALTINÝÐNE - 150130132
* BÜYÜK HARFLERÝ KARÞI BÝLGÝSYARA ATMA

	BAÞ $1000
	VER $1A, $27, $49, $28, $4A, $2B, $20, $50, $9, $6C, $2, $45, $56, $69, $7B, $63, $4C			KARAKTERLER YÜKLENDÝ
	VER $4F, $67, $41, $70, $40, $52, $59, $65, $1, $47, $5A, $44, $3, $2F, $19, $48, $66
	BAÞ $300

BAÞLA ALT KOÞUL					KOÞULA DALLAN
	YÜK SK ,$1000				SK'YA ÝLK VERÝNÝN ADRESÝNÝ YÜKLE

GERÝ	YÜK B, <SK+00>				B'YE ÝLK VERÝ YÜKLENDÝ
		
YOKLA	YÜK A, <DURDEN.B>				A'YA DURUM DENETÝM KÜTÜÐÜ YOLLANDI
	VE A, $80					%10000000 ÝLE VE'LENDÝ HAZIR OLDUÐUNU ANLAMAK ÝÇÝN
	DEE YOKLA					DEÐÝLSE HAZIR OLANA KADAR YOKLA
	
KARÞI	KAR B, $41					B'DEKÝ VERÝ KARÞILAÞTIRILDI $41 ÝLE $5A NIN ARASINDA OLMASI LAZIM (DAHÝL)
	DEK YENÝ					DEÐÝLSE B'YE YENÝ SAYI OKUNMAK ÝÇÝN YENÝYE DALLAN
	KAR B, $5A
	DEB YENÝ
	YAZ B, <ÝSKELE.B>				KOÞULLAR SAÐLANDIYSA ÝSKELE B'YE VERÝ ATILDI
	SÝL 4, <DURDEN.B>				4. GÖZE SÝLÝNDÝ SONRA TEKRAR 1 YAPILDI AL ÇIKIÞI 1 KONUMUNA GETÝRÝLDÝ
	KUR 4, <DURDEN.B>
	KAR SK, $2000				EÐER $2000'DEN OKUNDUYSA BÝTÝR
	DED GERÝ
	KES

YENÝ	ART SK					YENÝ KARAKTERÝ OKU
	YÜK B, <SK+00>				KARÞILAÞTIRMAYA DALLAN
	DAL KARÞI

KOÞUL YÜK A, $FF					A'YA FF YÜKLENDÝ
	YAZ A, <YÖNLEN.B>				PÝA A VERÝCÝ OLARAK AYARLANDI
	YÜK A, $10					PÝA A'NIN DURUM DENETÝM KÜTÜÐÜNE %00010000 YÜKLENDÝ
	YAZ A, <DURDEN.B>
	DÖN