* CAN YILMAZ ALTINÝÐNE - 150130132
* BELLEKTEN OKUNAN DEÐERE GÖRE DÝZÝNÝN O SIRADAKÝ ELEMANINI GETÝRME

	BAÞ $10			10 ADRESÝNE KAÇINCI SIRAYI ÝSTEDÝÐÝMÝZ YAZIYORUZ
	VER $5
	BAÞ $100								100 ADRESÝNDE BAÞLAYARAK DÝZÝMÝZÝ YAZARIZ
	VER $A1,$A2,$A3,$A4,$A5,$A6,$A7,$A8,$A9,$AA
	BAÞ $200								PROGRAM 200'DEN BAÞLAR

BAÞLA	YÜK SK, $FF			SK'YA 100'DEN BÝR ÖNCEKÝ ADRES YÜKLENDÝ
	YÜK C, $0			C'YE 0 YÜKLENDÝ
	YÜK D, <$10>		D'YE MÝKTAR YÜKLENDÝ (10 ADRESÝNDEKÝ)
	YÜK A, <CD+SK+00>		A'YA CD+SK'DEKÝ VERÝ YÜKLENDÝ
	YAZ A, <$20>		A'DAKÝ VERÝ 20 ADRESÝNE YAZILMIÞTIR
	KES

* SK FF'DEN BAÞLATILMIÞTIR ÇÜNKÜ 10 ADRESÝNDEKÝ SAYI 1 OLURSA DÝZÝNÝN ÝLK ELEMANINI 20'YE YAZMAK ÝSTÝYORUZ
* 5 OLURSA 5. ELEMANI 20'YE YAZMAK ÝSTÝYORUZ
* 10 ADRESÝNDEKÝ SAYI 0'DAN BÜYÜK DÝZÝ UZUNLUÐUNUN BÝR FAZLASINDAN KÜÇÜK OLMALIDIR



	